server:
  port: 8181

spring:
  application:
    name: baas-playlists

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
